# Generated by Django 6.0 on 2025-12-20 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery', models.CharField(max_length=50, verbose_name='Lotería')),
                ('draw_time', models.CharField(max_length=20, verbose_name='Hora del Sorteo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Jugada')),
                ('game_type', models.CharField(max_length=20)),
                ('bet_type', models.CharField(max_length=30, verbose_name='Tipo de Apuesta')),
                ('play_value', models.CharField(max_length=50, verbose_name='Número/Animal')),
                ('extras', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalles/Permutas')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Apostado')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('ganador', 'Ganador'), ('perdedor', 'No Ganador')], default='pendiente', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
