# Generated by Django 6.0 on 2025-12-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
