# Generated by Django 6.0 on 2025-12-23 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['date', 'lottery', 'draw_time'], name='core_result_date_8a7386_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['lottery', 'draw_time'], name='core_ticket_lottery_c9204e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='core_ticket_status_f5a85f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='core_ticket_created_fe6f19_idx'),
        ),
    ]
