# Generated by Django 6.0 on 2025-12-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='notification_seen',
            field=models.BooleanField(default=False),
        ),
    ]
